Single file multi-threading (read-only)
JuliaIO/JLD2.jl pull request #477
Opened 2023-07-22 15:21 UTC by ejmeitz

This PR aims to add support for multi-threaded read-only access to JLD2 files. I created a new global tracker `OPEN_PARALLEL_FILES` which keeps track of the files flagged as open for multi-threaded access. The flag for multi-threaded access was added to the `jldopen` function as `parallel_read` with a default of false. If the user changes this flag to true the program will check that the file is opened with in mode `r` and that it is not already present in the `OPEN_FILES` list. If these checks are satisfied `jldopen` proceeds as normal. The `OPEN_FILES_LOCK` is not invoked when `parallel_read` is true.

This is in reference to #403. Still need to add tests, but the existing tests still pass.

Things I was unsure of:
- Do I need to verify compression types are passed the same each time? (other flags as well)

2023-07-23 19:12 UTC, JonasIsensee requested changes
Hi

thank you for your contribution!

At this stage, this PR will not do what we want it to do.

I like the new keyword argument and that you check for the file to be in read-only mode.
However, the `JLDFile` object doesn not support parallel access.
To circumvent that, this PR must return a new `JLDFile` instance every time you do `jldopen(filename)`.

Possibly contrary to what I said earlier, maybe we don't need to keep track of `OPEN_PARALLEL_FILES`. Currently it can't hold multiple file handles of the same file anyway. The only advantage would be to throw an error when a user first opens a `parallel-read` file handle, then edits the file in regular mode and continues to read with the original file handle.

2023-07-23 19:12 UTC, JonasIsensee commented on src/JLD2.jl
> +    parallel_read && lock(OPEN_FILES_LOCK)
I believe this should be an `||`

2023-07-23 19:12 UTC, JonasIsensee commented on src/JLD2.jl
> +    parallel_read && lock(OPEN_FILES_LOCK)
also, the below must be wrapped in something like
```
try

finally
unlock(OPEN_FILES_LOCK)
end
```
Otherwise an uncaught exception will break JLD2.

2023-07-23 19:12 UTC, JonasIsensee commented on src/JLD2.jl
>                      return f
Sadly, I think, this does not solve the problem at all.

With this logic you still just end up with a single open file handle.
This should should return a new file handle each time.

2023-07-23 19:28 UTC, ejmeitz commented
Makes sense, that shouldn't be too hard to remedy.

2023-07-23 19:54 UTC, ejmeitz commented on src/JLD2.jl
> +    parallel_read && lock(OPEN_FILES_LOCK)
My idea with the lock was to only use it if the users is reading the files normally. Do you think I still need some kind of lock on the file handles with the parallel access?

2023-07-23 20:07 UTC, ejmeitz commented on src/JLD2.jl
> +    parallel_read && lock(OPEN_FILES_LOCK)
I guess this is unnecessary if every parallel access gets a new file handle.

2023-07-23 20:10 UTC, ejmeitz commented
Well the code definitely makes a new handle every time if `parallel_read` is true but I am still clueless as to how I can test this does what I think it does.

2023-07-23 20:13 UTC, JonasIsensee commented
> Why the BigInt tests fails on two of the architectures in the CI (passes locally for me)
Don't worry about this one. It happens sporadically. I'm not sure why.

2023-07-23 20:18 UTC, JonasIsensee commented
Thank you for making the changes!

That is fine - I don't think we can properly test this through CI. I'll have a final close look at the code and test it locally.

Looking at the code now, I don't think I like the "OPEN_PARALLEL_FILES" list. I think we're better off without it.

Also, you (probably accidentally) committed a manifest and a `.jld2` file.

2023-07-23 21:01 UTC, ejmeitz commented
- I'll try and test it out as well. I have some of the banned use cases in tests but not actual parallel reads.
- I left the `OPEN_PARALLEL_FILES` to check that case you mentioned of someone trying to open the same file elsewhere with `parallel_read` set to false and then writing to that file.
- Yeah the manifest is from running the tests locally oops.

2023-07-24 10:14 UTC, JonasIsensee commented
> * I'll try and test it out as well. I have some of the banned use cases in tests but not actual parallel reads.

:+1: 

>     * I left the `OPEN_PARALLEL_FILES` to check that case you mentioned of someone trying to open the same file elsewhere with `parallel_read` set to false and then writing to that file.

I understand and appreciate the intention. I'd also support it if it were that simple.
Imagine the following test-case.
```
fp = jldopen(testfile; parallel_read=true)
close(fp) # probably (already) fails because it can't be deleted from the OPEN_FILES Dict

fs = jldopen(testfile; parallel_read=false) # fails because OPEN_PARALLEL_FILES has an entry (that may be WeakRef(nothing))
```

Even harder to fix:
```
fp1 = jldopen(testfile; parallel_read=true)
fp2 = jldopen(testfile; parallel_read=true) # overwrites reference tot fp1
close(fp2)

# If you fix the case above, JLD2 would now still think that there is no open parallel file handle.
fs = jldopen(tesfile; parallel_read=false) # should fail according to current logic but doesn't  
```


Since this is quite a bit of work (Would need to keep a full list of ALL open file handles and also check whether they are still open) I would prefer removing this safety check and add a warning in the docs instead.

 
>     * Yeah the manifest is from running the tests locally oops. It won't let me delete the test.jld2 file I committed for some reason.

That's fine. I can fix that in the end.

2023-07-26 06:50 UTC, JonasIsensee commented
Hi @ejmeitz,

thanks for helping out!
I had a few minutes to spare and took the liberty to finish this up real quick.

I relaxed the open conditions. (parallel and serial read is fine)
Will merge and release once tests pass.

2023-07-26 07:14 UTC, JonasIsensee approved these changes

2023-07-26 07:14 UTC, merged

2024-09-25 18:38 UTC, JonasIsensee commented
@ZenanH 
The JLD2 part looks fine by itself.
You are reusing the iteration variable i a bunch of times. You could check that this is not accidentally messing things up in the rest of your code.

2024-09-25 20:56 UTC, ejmeitz commented
I use this feature in my code and it works correctly, so I think JLD2 is fine.  I don't really understand your code but there could be a race condition in there somewhere. Its hard to know if the issue is JLD2 or elsewhere.